Add KNN and MIP functions
broadinstitute/hidive pull request #20
Opened 2024-08-07 23:53 UTC by hangsuUNC

Hi Kiran,

I rebased the branch and added a few functions about MIP and KNN stuff in assemble.rs. Could you please help to merge this branch to main? 

Thanks,

Hang

2024-08-09 19:24 UTC, kvg requested changes

2024-08-09 19:24 UTC, kvg commented on src/hidive/Cargo.toml
> +<<<<<<< HEAD
Looks like there are some unresolved rebase issues here causing the build to fail. Can you address these?

2024-08-09 19:24 UTC, kvg commented on src/skydive/Cargo.toml
> +=======
Here too.

2024-08-09 19:57 UTC, hangsuUNC commented
Hi, I resolved some changes and hopefully there will be no conflicts now...

Please let me know if you need anything else!

Thanks,

Hang

2024-08-09 20:00 UTC, kvg commented
Thanks! Don't forget to mark your branch as ready for review!

2024-08-10 01:08 UTC, kvg commented
There seems to be a build failure related to this commit - is there something else we need to add to the Docker image before this will build successfully?

https://github.com/broadinstitute/hidive/actions/runs/10324946547/job/28585508145?pr=20#step:5:6739

2024-08-10 15:52 UTC, hangsuUNC commented
> There seems to be a build failure related to this commit - is there something else we need to add to the Docker image before this will build successfully?
> 
> https://github.com/broadinstitute/hidive/actions/runs/10324946547/job/28585508145?pr=20#step:5:6739

It seems the build failed to install rust-wfa2 with `#12 210.9 error: failed to run custom build command for wfa2-sys v0.1.0 (https://github.com/pairwise-alignment/rust-wfa2.git#4cbfeb3d)`. I can build and compile this package from github repository in the local laptop though...

2024-08-13 13:54 UTC, kvg commented
I see.  Can you work with @SHuang-Broad or @bshifaw to get this build issue resolved before we merge this in?

2024-08-14 20:17 UTC, merged